config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tunes#index"
  resources :tunes do
    resources :comments, only: :create
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  validates :text, presence: true 
  
  belongs_to :tune
  belongs_to :user 
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1960年代' },
    { id: 3, name: '1970年代' },
    { id: 4, name: '1980年代' },
    { id: 5, name: '1990年代' },
    { id: 6, name: '2000年代' },
    { id: 7, name: '2010年代' },
    { id: 8, name: 'J-POP' },
    { id: 9, name: 'R&B' },
    { id: 10, name: 'アコーステック' },
    { id: 11, name: '歌謡曲' },
    { id: 12, name: 'キッズ/ファミリー' },
    { id: 13, name: 'クラシック' },
    { id: 14, name: 'ジャズ' },
    { id: 15, name: 'ロック' },
    { id: 16, name: 'HIPHOP' },
    { id: 17, name: 'REGGAE' },
    { id: 18, name: '洋楽' },
    { id: 19, name: 'EDM' },
    { id: 20, name: 'その他' }
  ]
  include ActiveHash::Associations
  has_many :tunes
  end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user 
  belongs_to :follower, class_name: 'User'
end

app/models/tune.rb
class Tune < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments

  with_options presence: true do
    validates :name
    validates :url 
    validates :artist
    validates :genre_id
    validates :text
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :genre_id
  end

  validates :text, length: { maximum: 15 }
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 with_options presence: true do
  validates :nickname
  validates :password_confirmation
  validates :year
  validates :introduction
 end

 validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }

 has_many :tunes, dependent: :destroy
 has_many :comments
 has_many :relationships, dependent: :destroy
 has_many :followings, through: :relationships, source: :follower
 has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy 
  has_many :followers, through: :passive_relationships, source: :user 

  def follow(other_user)
    return if self == other_user

    relationships.find_or_create_by!(follower: other_user)
  end

  def following?(user)
    followings.include?(user)
  end

  def unfollow(relathinoship_id)
    relationships.find(relathinoship_id).destroy!
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email, :password, :password_confirmation, :year, :introduction])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    redirect_to tune_path(@comment.tune.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, tune_id: params[:tune_id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @other_user = User.find(params[:follower])
    current_user.follow(@other_user)
    respond_to do |format|
      format.html {redirect_back(fallback_location: root_url)}
      format.js
    end
     
  end

  def destroy
    @user = current_user.relationships.find(params[:id]).follower
    current_user.unfollow(params[:id])
    respond_to do |format|
      format.html {redirect_back(fallback_location: root_url)}
      format.js
    end
      
  end

end

app/controllers/tunes_controller.rb
class TunesController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
before_action :set_tune, only: [:edit,:show, :update, :destroy]
before_action :move_to_index, only: [:edit, :update, :destroy]


  def index
    @tunes = Tune.includes(:user).order("created_at DESC")
  end

  def new
    @tune = Tune.new
  end

  def create
    @tune = Tune.create(tune_params)
    if @tune.save
      redirect_to tunes_path
    else
      render :new
    end
  end

  def destroy
   @tune.destroy
  end

  def edit
   
  end

  def update
    @tune.update(tune_params)
  end

  def show
    @comment = Comment.new
    @comments = @tune.comments.includes(:user)
  end

  private
  def tune_params
    params.require(:tune).permit(:url, :name, :artist, :genre_id, :text, :user, :image).merge(user_id: current_user.id)
  end 

  def set_tune
    @tune = Tune.find(params[:id])
  end

  def move_to_index
    unless user_signed_in? && @tune.user.id == current_user.id
      redirect_to action: :index
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @tunes = @user.tunes
    @followers = @user.relationships
  end

  def edit
    @user = User.find(params[:id])
    if user_signed_in? && current_user.id == @user.id
      render "edit"
    else
      redirect_to root_path
    end
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :year, :introduction)
  end


  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turnapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6">
         <%= link_to image_tag("turnapp-logo.jpg", class:"app-icon"), "/" %>
         </h1>
         <% if user_signed_in? %>
          <div class="user_nav grid-6">
           <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", user_path(current_user.id) %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
            <%= link_to "投稿する", new_tune_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
     <footer>
      <p>
        Tune App 2021
      </p>
    </footer>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<%= button_to 'フォロー', relationships_path(follower: user), remote: true %>

app/views/relationships/_unfollow_button.html.erb
<%=button_to 'フォロー解除', relationship_path(current_user.relationships.find_by(follower: user)), method: :delete, remote: true %>

app/views/relationships/create.js.erb
$("#follow-button").html("<%= j(render 'unfollow_button', user: @other_user) %>")

app/views/relationships/destroy.js.erb
$("#follow-button").html("<%= j(render 'follow_button', user: @user) %>")

app/views/tunes/_error_messages.html.erb
<% if model.errors.any? %>

<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'>*<%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>

app/views/tunes/_form.html.erb
 <%= form_with model: tune,local: true do |f| %>

    <%= render 'error_messages', model: f.object %>

      <%# イメージ画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        イメージ画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"tune-image" %>
      </div>
       <div id="image-list"></div>
    </div>
    <%# /イメーじ画像 %>
     <%# 曲名と曲説明 %>
    <div class="new-tunes">
    <div class="weight-bold-text">
        YouTubeのURL
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :url, class:"tunes-url", id:"tune-url", placeholder:"YouTubeのURL" %>

      <div class="weight-bold-text">
        曲名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"tunes-text", id:"tune-name", placeholder:"曲名" %>
      <div class="tunes-explain">
        <div class="weight-bold-text">
          お好きにどうぞ
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"tunes-text", id:"tune-info", placeholder: "ご自由に感じたことを（必須 15文字まで)" ,maxlength:"15" %>
        <div class="weight-bold-text">
        アーティスト名
        <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :artist,class:"tunes-artist", id:"tune-artist",placeholder: "アーティスト名" %>
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all , :id, :name, {}, {class:"select-box", id:"tune-category"}) %>
      </div>
      </div>
    <%# /曲名と曲説明 %>
     <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
    <% end %>

app/views/tunes/_tune.html.erb
<div class="content_post" >
     <%= image_tag tune.image, class: "tune-img"  %>
       <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', tune_path(tune.id), method: :get %>
          </li>
           <% if user_signed_in? && current_user.id == tune.user_id %>
          <li>
            <%= link_to '編集', edit_tune_path(tune.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tune_path(tune.id), method: :delete %>
          </li>
          <%end%>
        </ul>
      </div>
</div>

app/views/tunes/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tunes/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/tunes/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
   <%= render partial: "form", locals: { tune: @tune } %>
  </div>
</div>

app/views/tunes/index.html.erb
<div class="contents row">
  <% @tunes.each do |tune| %>
   <%= render partial: "tune", locals: {tune: tune} %>
  <% end %>
</div>

app/views/tunes/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @tune, local: true) do |f| %>
      <%# イメージ画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        イメージ画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"tune-image" %>
      </div>
       <div id="image-list"></div>
    </div>
    <%# /イメーじ画像 %>
     <%# 曲名と曲説明 %>
    <div class="new-tunes">
    <div class="weight-bold-text">
        YouTubeのURL
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :url, class:"tunes-url", id:"tune-url", placeholder:"YouTubeのURL" %>

      <div class="weight-bold-text">
        曲名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"tunes-text", id:"tune-name", placeholder:"曲名" %>
      <div class="tunes-explain">
        <div class="weight-bold-text">
          お好きにどうぞ
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduction, class:"tunes-text", id:"tune-info", placeholder: "ご自由に感じたことを（必須 15文字まで)" ,maxlength:"15" %>
        <div class="weight-bold-text">
        アーティスト名
        <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :artist,class:"tunes-artist", id:"tune-artist",placeholder: "アーティスト名" %>
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all , :id, :name, {}, {class:"select-box", id:"tune-category"}) %>
      </div>
      </div>
    <%# /曲名と曲説明 %>
     <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
    <% end %>
  </div>
</div>

app/views/tunes/show.html.erb
    <div class="contents row">

     <div class="tune-explain-box">
      <span><%=@tune.text %></span>
    </div>

    <div class="show-img">
   <%= link_to image_tag(@tune.image) , @tune.url %>
      <p>*画像をクリックするとYouTubeに移動します。</p>
      </div>

       
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者名</th>
          <td class="detail-value">
          <%= link_to @tune.user.nickname, user_path(@tune.user.id) %>
          </td>
        </tr>
        <tr>
          <th class="detail-item">曲名</th>
          <td class="detail-value"><%= @tune.name%></td>
        </tr>
        <tr>
          <th class="detail-item">アーティスト名</th>
          <td class="detail-value"><%= @tune.artist %></td>
        </tr>
        <tr>
          <th class="detail-item">曲のジャンル</th>
          <td class="detail-value"><%= @tune.genre.name %></td>
        </tr>
       </tbody>
    </table>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@tune, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
    </div>

app/views/tunes/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>更新が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/users/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>ユーザー情報編集</h2>
    <%= form_with model: current_user, url: user_path, local: true do |f| %>
      

      <div class="weight-bold-text">
        ニックネーム
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) 音スキ" %>

       <div class="weight-bold-text">
        年齢
        <span class="indispensable">必須</span>
      </div>
    <%= f.number_field :year, class:"input-default", id:"year", placeholder:"例) 22" %>

     <div class="weight-bold-text">
        自己紹介
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :introduction, class:"input-default", id:"introduction", placeholder:"例) 大阪府在住の22歳 男です。好きな音楽のジャンルはロックです。 よろしくお願いします。" %>
      

      <div class="weight-bold-text">
        メールアドレス
        <span class="indispensable">必須</span>
        <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
      </div>
        
    

      <div class="weight-bold-text">
        パスワード
        <span class="indispensable">必須</span>
      <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    </div>

     <div class="weight-bold-text">
        パスワード(確認用)
        <span class="indispensable">必須</span>
        <%= f.password_field :password_confirmation, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "ユーザー情報更新" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
<div class="user-show">
<%= @user.year%>歳の<%=@user.nickname%>さん
<div class="user-introduction">
<%=@user.introduction%>
</div>
<% if user_signed_in? && current_user.id == @user.id %>
<%= link_to "編集する", edit_user_path(@user) %>
<% end %>
</div>

<div class="follower">
フォローしたユーザー
<div class="follow-link">
<% @followers.each do |follower| %>
<%= link_to follower.follower.nickname, user_path(follower.follower.id) %>
<%end%>
</div>
</div>

  <p><%= @nickname %>さんの投稿一覧</p>
  <% @tunes.each do |tune| %>
    <div class="content_post" style="background-image: url(<%= tune.image %>);">
    <%= image_tag tune.image, class: "tune-img" %>
    <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', tune_path(tune.id), method: :get %>
          </li><% if user_signed_in? && current_user.id == tune.user_id %>
          <li>
            <%= link_to '編集', edit_tune_path(tune.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', tune_path(tune.id), method: :delete %>
          </li>
          <%end%>
          </ul>
          </div>
      <p><%= tune.text %></p>
      <span class="name"><%= tune.name + "/" + tune.artist %></span>
      </div>
  <% end %>

  <% if user_signed_in? && current_user != @user %>
  <div id= "follow-button" >
  <% if current_user.following?(@user) %>
    <%= render "relationships/unfollow_button", user: @user %>
  <%else%>
    <%= render "relationships/follow_button", user: @user%>
    <%end%>
  </div>
    <%end%>